### ISSUE TITLE
.Travis.yml file not found error.

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/bodyapps-viz#13]
The Travis configuration file is not found due to which Travis reverts to Ruby configuration, hence Travis build fails.

**Comment by jayvdb** [comment]
https://github.com/fossasia/bodyapps-viz/commit/56a56eee8d - whoops

**Comment by abishekvashok** [comment]
It has to be `.travis.yml` and not `travis.yml`
CC: @jayvdb @mariobehling
